CREATE TABLE DEAD_ORDER_EVENT
(
    ORDERID CHARACTER VARYING(128) NOT NULL,
    EVENTID CHARACTER VARYING(128) NOT NULL,
    TENANTID CHARACTER VARYING(128) NOT NULL
)  TABLESPACE :pg_tablespace;

ALTER TABLE ONLY DEAD_ORDER_EVENT ADD CONSTRAINT DEAD_ORDER_EVENT_PK PRIMARY KEY (ORDERID, EVENTID, TENANTID);