CREATE OR REPLACE FUNCTION app_properties_change()
RETURNS TRIGGER
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
	curr_timestamp NUMERIC(25,0);
BEGIN

	curr_timestamp = ROUND(EXTRACT(EPOCH FROM now()) * 1000);

	IF (TG_OP = 'DELETE') THEN
		INSERT INTO app_properties_events VALUES (OLD.KEY, OLD.VALUE, OLD.APPLICATION, OLD.VALUETYPE, OLD.PROPERTYDESCRIPTION, OLD.CATEGORY, OLD.ISTENANTPROPERTY, OLD.APPDESCRIPTION, OLD.ALLOWEDVALUES, TG_OP,curr_timestamp, NULL);
	ELSIF (TG_OP = 'INSERT') THEN
		INSERT INTO app_properties_events VALUES (NEW.KEY, NEW.VALUE, NEW.APPLICATION, NEW.VALUETYPE, NEW.PROPERTYDESCRIPTION, NEW.CATEGORY, NEW.ISTENANTPROPERTY, NEW.APPDESCRIPTION, NEW.ALLOWEDVALUES, 'ADD',curr_timestamp, NEW.lastmodifiedbyuser);
	ELSE
		INSERT INTO app_properties_events VALUES (NEW.KEY, NEW.VALUE, NEW.APPLICATION, NEW.VALUETYPE, NEW.PROPERTYDESCRIPTION, NEW.CATEGORY, NEW.ISTENANTPROPERTY, NEW.APPDESCRIPTION, NEW.ALLOWEDVALUES, TG_OP,curr_timestamp, NEW.lastmodifiedbyuser);
	END IF;
    RETURN NULL;

END;
$BODY$;