apiVersion: v1
kind: Pod
metadata:
  name: {{ template "postgres.fullname" . }}-init-admin-db-deployment
  labels:
  {{- include "initAdminDb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  containers:
    - name: init-admin-db-container
      image: "{{ .Values.initAdminDb.image }}"
      command: [ "/bin/bash" ]
      args: [ "-c", "cd /home/tibuser/tibco/om/5.1/configurator/standalone/bin && bash ./seedConfigData.sh" ]
      imagePullPolicy: {{ .Values.initAdminDb.pullPolicy }}
      env:
        - name: adminDsUrl
          value: {{ .Values.initAdminDb.env.adminDsUrl }}
  restartPolicy: OnFailure