apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-order-db-bin-scripts
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "postgresql.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- with .Files.Glob "files/dbscripts/order/bin/*.{sh,properties}" }}
{{ .AsConfig | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-order-db-sql-scripts
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "postgresql.tplValue" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- with .Files.Glob "files/dbscripts/order/scripts/*.sql" }}
{{ .AsConfig | indent 2 }}
{{- end }}